name: femm
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.19.0
  date_picker_timeline: ^1.2.6
  easy_date_timeline: ^1.1.3
  timeline_tile: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_riverpod: ^2.5.1
  firebase_core:
  firebase_auth: ^5.3.1
  fluttertoast: ^8.2.8
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/images/splash_gradient.png
    - asset/images/card_grad.png

  fonts:
    - family: montserrat
      fonts:
        - asset: asset/fonts/montserrat/Montserrat-Regular.otf
    - family: Public sans
      fonts:
        - asset: asset/fonts/public_sans/PublicSans-Regular.ttf
